config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :task_lists
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "task_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :bigint           not null, primary key
#  title        :string
#  status       :boolean
#  task_list_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  deleted_at   :datetime
#
class Task < ApplicationRecord

  # paranoia
  acts_as_paranoid

  belongs_to :task_list
end

app/models/task_list.rb
# == Schema Information
#
# Table name: task_lists
#
#  id         :bigint           not null, primary key
#  name       :string
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#
class TaskList < ApplicationRecord
  # paranoia
  acts_as_paranoid
  scope :ordered, -> { order(id: :desc) }

  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, length: { minimum: 8, message: 'Texto curto demais' }

  def self.ransackable_attributes(auth_object = nil)
    ['name']
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :task_lists, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :password_validate

  def password_validate
    return if password =~ /^(?=.*[A-Za-z])(?=.*\d).{8,}$/

    errors.add :password, 'A senha deve conter pelo menos um número e ter no mínimo 8 caracteres'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @tasks_lists = TaskList.all
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: %i[show edit update destroy]

  # GET /task_lists or /task_lists.json
  def index
    @q = TaskList.ransack(params[:q])
    @task_lists = @q.result(distinct: true).where(user_id: current_user.id).ordered
  end

  # GET /task_lists/1 or /task_lists/1.json
  def show; end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit; end

  # POST /task_lists or /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)
    @task_list.user_id = current_user.id
    respond_to do |format|
      if @task_list.save
        format.html { redirect_to task_list_url(@task_list), notice: t('.success') }
        format.json { render :show, status: :created, location: @task_list }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1 or /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to task_lists_path, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1 or /task_lists/1.json
  def destroy
    set_task_list
    @task_list.destroy
    flash[:notice] = t('task_lists.destroy.success')
    respond_to do |format|
      format.html { redirect_to task_lists_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task_list
    @task_list = TaskList.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_list_params
    params.require(:task_list).permit!
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks or /tasks.json
  def index
    respond_to do |format|
      format.html { redirect_to "/500", notice: "Rota não existente" }
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task_list_id = params[:task_list_id]
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: t(".success") }
        format.json { render :show, status: :created, location: @task }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :status, :task_list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
   case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
   end
  end
end

app/helpers/icons_helper.rb
module IconsHelper
  def trash_icon
    '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
      <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
    </svg>'.html_safe
  end

  def pencil_icon
    '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
      <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
    </svg>'.html_safe
  end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header>
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="#">Just To Do </a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">


                  <%= search_form_for @q do |f|%>
                    <%= f.search_field :name_cont , class: "form-control", placeholder: "Task List..."%>
                  <% end %>
                    <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="index.html.erb"><%=  button_to "logout", destroy_user_session_path, method: :delete , class: "dropdown-item"%></a></li>
                    </ul>
                </li>
            </ul>
        </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustToDo2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/task_lists/_form.html.erb
<%= form_with(model: task_list) do |form| %>
  <% if task_list.errors.any? %>
      <ul>
        <% task_list.errors.each do |error| %>
          <li class="text-danger"><%= error.message %></li>
        <% end %>
      </ul>
  <% end %>
  <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center input-group">
    <%= form.text_field :name, 
        placeholder: I18n.t('attributes.task_list.name'), 
        data: {action: "input->custom#update_hint", 
        custom_target: "nameTaskList"},
        class: 'form-control' %>
    <h3 id="new_task_list_title"></h3>
    <%= form.submit (I18n.t('task_lists.form.create')) , class: 'btn btn-info rounded' %>
  </div>
<% end %>

app/views/task_lists/_task_list.html.erb
<div class="list-group animation_new_task">
  <div class="list-group-item list-group-item-action d-flex flex-row justify-content-between gap-3 mb-3">
    <div>
      <%= render "utils/hash" %>
      <%= link_to task_list.name , task_list_path(task_list), class: '' %>
    </div>
    <div class="text-end d-flex">
       <%= link_to pencil_icon,
        edit_task_list_path(task_list), class: 'btn', data: {turbo_frame: "new_task_list"}%>
      <%= button_to trash_icon,
        task_list_path(task_list), method: :delete, data: {turbo_confirm: 'Quer mesmo fazer isso?'}, class: 'btn'%>
    </div>
  </div>
</div>

app/views/task_lists/create.turbo_stream.erb
<%= turbo_stream.prepend("task_list", @task_list)%>

app/views/task_lists/edit.html.erb
<%= turbo_frame_tag "new_task_list" do %>
  <div class="pop-up">
    <div class="overlay"></div>
      <div class="modal-custom">
        <div class="position-relative">

          <h1>Editing task list</h1>

          <%= render "form", task_list: @task_list %>

          <br>

          <div>
            <%= link_to "Show this task list", @task_list %> |
            <%= link_to "Back to task lists", task_lists_path %>
          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/task_lists/index.html.erb
<%= render "layouts/header"%>
<div id="task_lists" class= "container mt-5">
  <% if flash[:notice] %>
    <div class="<%= flash_class(:success)%>"><%= flash[:notice] %></div>
  <% end %>
  <% @task_lists.each do |task_list| %>
    <div id="task_list">
      <div class="">
        <div class="">
          <div class="mt-2">
            <%= render 'task_list', task_list:  %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= turbo_frame_tag "new_task_list"%>
  <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
      <%= link_to "Nova lista", new_task_list_path, class: 'btn btn-primary button__new_task_list', data: {turbo_frame: "new_task_list"} %>
  </div>
</div>

app/views/task_lists/new.html.erb
<%= turbo_frame_tag "new_task_list" do %>
  <div class="pop-up">
    <div class="overlay"></div>
    <div class="modal-custom">
        <div class="position-relative">
          <h1><%= render 'utils/action_name'%>:
            <span id="new_task_list_title"></span>
          </h1>
          <%= render "form", task_list: @task_list %>
          <br>
          <div>
            <%= link_to "Back to task lists", task_lists_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/task_lists/show.html.erb
<div class="task-list card container mt-4">
  <h2><%= @task_list.name %></h2>
  <div class="tasks" id="tasks">
    <% @task_list.tasks.each_with_index do |task, index| %>
      <%= render "tasks/task", task: , class_personalized: 'task-list__task'%>
    <% end %>
    <%= link_to 'New Task',new_task_path(task_list_id: @task_list), data: {turbo_frame: "new_task"} %>
  </div>
  <div>
    <%= link_to "Edit this task list", edit_task_list_path(@task_list) %> |
    <%= link_to "Back to task lists", task_lists_path %>

    <%= button_to "Destroy this task list", @task_list, method: :delete, data: {turbo_confirm: 'Quer mesmo fazer isso?'} %>
  </div>
</div>
<%= turbo_frame_tag "new_task"%>

app/views/task_lists/update.turbo_stream.erb
<%= turbo_stream.replace("task_list", @task_list) %>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div style="display:none;">
    <%= form.label :task_list_id, style: "display: block" %>
    <%= form.text_field :task_list_id, value: @task_list_id %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="card">
  <h4>
    <strong>Title:</strong>
    <%= task.title %>
  </h4>

  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>

</div>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.prepend("tasks", @task) %>

app/views/tasks/edit.html.erb
<h1><%= render "utils/action_name"%></h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "new_task" do %>
  <div class="pop-up">
    <div class="overlay"></div>
    <div class="modal-custom">
      <div class="position-relative">
        <h1><%= render "utils/action_name"%></h1>
        <%= render "form", task: @task %>
        <br>
        <div>
          <%= link_to "Back to tasks", task_lists_path(@task.task_list) %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/utils/_action_name.html.erb
<%= (I18n.t("actions.#{action_name}")) + " " +I18n.t("models.#{controller_name}") %>

app/views/utils/_hash.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hash" viewBox="0 0 16 16">
  <path d="M8.39 12.648a1 1 0 0 0-.015.18c0 .305.21.508.5.508.266 0 .492-.172.555-.477l.554-2.703h1.204c.421 0 .617-.234.617-.547 0-.312-.188-.53-.617-.53h-.985l.516-2.524h1.265c.43 0 .618-.227.618-.547 0-.313-.188-.524-.618-.524h-1.046l.476-2.304a1 1 0 0 0 .016-.164.51.51 0 0 0-.516-.516.54.54 0 0 0-.539.43l-.523 2.554H7.617l.477-2.304c.008-.04.015-.118.015-.164a.51.51 0 0 0-.523-.516.54.54 0 0 0-.531.43L6.53 5.484H5.414c-.43 0-.617.22-.617.532s.187.539.617.539h.906l-.515 2.523H4.609c-.421 0-.609.219-.609.531s.188.547.61.547h.976l-.516 2.492c-.008.04-.015.125-.015.18 0 .305.21.508.5.508.265 0 .492-.172.554-.477l.555-2.703h2.242zm-1-6.109h2.266l-.515 2.563H6.859l.532-2.563z"/>
</svg>